### ISSUE TITLE
train_api_request和complete_gpt3区别在哪

### ISSUE THREAD

**Issue by steveluo01** [shizhediao/Black-Box-Prompt-Learning#2]
for m, missing_batch in enumerate(batches['sentence']):
            if split == "train":
                missing_response = train_api_request(missing_batch, l=0, model_name=args.model_name_or_path, num_log_probs=1, echo=True)
            else: 
                missing_response = complete_gpt3(missing_batch, l=0, model_name=args.model_name_or_path, num_log_probs=1, echo=True)

train_api_request和complete_gpt3区别在哪

**Comment by shizhediao** [comment]
感谢关注！
train_api_request的目的是为了计算API调用次数，于是在complete_gpt3的外层套了一个counter。

--------

Thanks for attention!
The purpose of `train_api_request` is to count the number of API calls, so a counter is set in the outer layer of complete_gpt3.
